version: "1.0.0"
#Docker compose file with a posgresql container and a web service with node js 
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: sample
    volumes:
      - ./data:/var/lib/postgresql/data