version: "1.0.0"
#Docker compose file with a posgresql container and a web service with node js 
services:
  #web:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "24:24"
  #  depends_on:
  #    - db
  #  environment:
  #    - DB_HOST=db
  #    - DB_USER=postgres
  #    - DB_PASSWORD=admin
  #    - DB_NAME=sample
  #    - DB_PORT=5432
  #  volumes:
  #    - .:/usr/src/app
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: sample
    volumes:
      - ./data:/var/lib/postgresql/data